### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by sandboiii** [harmony-development/winged_staccato#2]
I consider implementing the following things for v1:
- [x] Rename project and app
- [x] Change application icon
- [ ] Infinite scroll
- [ ] Attachments
- [ ] Preserving app state
- [ ] Emojis
- [ ] Profile view
- [ ] Editing messages
- [ ] Handling all of guild events
- [ ] Permissions and roles
- [ ] Enhance ui design
